# Site settings
title: Balazs Bencs
email: bencsbalazs@gmail.com
url: https://bencsbalazs.github.io

description: ""
keywords: "developer, agile, ibm, bencs, balázs"
copyright: "Bencs Balázs 2019"

lang: en

# Google webmaster tools
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
